import {
  AlertTriangle,
  ArrowLeftRight,
  BarChart3,
  Bot,
  Boxes,
  BrainCircuit,
  Building2,
  CalendarClock,
  ClipboardCheck,
  ClipboardList,
  Clock,
  FileClock,
  FileInput,
  FolderClosed,
  LayoutDashboard,
  MonitorPlay,
  PlusCircle,
  ScrollText,
  Settings,
  Sparkles,
  Trash2,
  Users,
  UsersRound,
  Warehouse,
  WandSparkles,
  BadgePercent,
  Inbox,
} from 'lucide-react';
import type { PageKey } from '@/types/pages';

export type NavItem = { key: PageKey; label: string; icon: typeof LayoutDashboard };

export const navItems: NavItem[] = [
  { key: 'dashboard', label: 'Bảng điều khiển', icon: LayoutDashboard },
  { key: 'products', label: 'Quản lý sản phẩm', icon: Boxes },
  { key: 'categories', label: 'Danh mục', icon: FolderClosed },
  { key: 'suppliers', label: 'Nhà cung cấp', icon: Building2 },
  { key: 'locations', label: 'Vị trí kho', icon: Warehouse },
  { key: 'pos', label: 'Quầy POS', icon: MonitorPlay },
  { key: 'customers', label: 'Khách hàng', icon: Users },
  { key: 'invoices', label: 'Hóa đơn', icon: FileInput },
  { key: 'import-create', label: 'Tạo phiếu nhập', icon: PlusCircle },
  { key: 'import-slips', label: 'Phiếu nhập kho', icon: ClipboardCheck },
  { key: 'inventory', label: 'Tồn kho', icon: Inbox },
  { key: 'scrap-orders', label: 'Yêu cầu loại bỏ', icon: Trash2 },
  { key: 'inventory-alerts', label: 'Cảnh báo tồn kho', icon: AlertTriangle },
  { key: 'inventory-logs', label: 'Lịch sử biến động', icon: ScrollText },
  { key: 'item-lots', label: 'Quản lý lô hàng', icon: Boxes },
  { key: 'stocktake', label: 'Kiểm kê kho', icon: ClipboardList },
  { key: 'transfer-orders', label: 'Chuyển kho', icon: ArrowLeftRight },
  { key: 'shifts', label: 'Ca làm việc', icon: Clock },
  { key: 'ai-forecast', label: 'Dự báo AI', icon: BrainCircuit },
  { key: 'purchase-suggestions', label: 'Gợi ý nhập hàng', icon: Bot },
  { key: 'expiry-risk', label: 'Rủi ro hết hạn', icon: CalendarClock },
  { key: 'promotions', label: 'Đề xuất KM (AI)', icon: WandSparkles },
  { key: 'promotion-manage', label: 'Quản lý mã KM', icon: BadgePercent },
  { key: 'ai-assistant', label: 'Trợ lý AI', icon: Sparkles },
  { key: 'reports', label: 'Báo cáo hệ thống', icon: BarChart3 },
  { key: 'users', label: 'Người dùng', icon: UsersRound },
  { key: 'settings', label: 'Cài đặt hệ thống', icon: Settings },
  { key: 'audit-logs', label: 'Nhật ký hệ thống', icon: FileClock },
];
