export type PageKey =
  | 'dashboard'
  | 'products'
  | 'categories'
  | 'brands'
  | 'suppliers'
  | 'locations'
  | 'uoms'
  | 'pos'
  | 'invoices'
  | 'return-orders'
  | 'quotations'
  | 'online-orders'
  | 'import-create'
  | 'import-slips'
  | 'inventory'
  | 'barcode-print'
  | 'expired-products'
  | 'inventory-alerts'
  | 'inventory-logs'
  | 'ai-forecast'
  | 'purchase-suggestions'
  | 'expiry-risk'
  | 'promotions'
  | 'promotion-manage'
  | 'discount-plans'
  | 'gift-cards'
  | 'customers'
  | 'customer-debts'
  | 'ai-assistant'
  | 'reports'
  | 'finance'
  | 'users'
  | 'settings'
  | 'scrap-orders'
  | 'stocktake'
  | 'shifts'
  | 'item-lots'
  | 'audit-logs';

export type PurchaseSuggestionPrefillItem = {
  itemId: number;
  suggestedQty: number;
};
