ALTER TABLE shifts ADD COLUMN IF NOT EXISTS variance_reason TEXT;
ALTER TABLE shifts ADD COLUMN IF NOT EXISTS reviewed_by BIGINT REFERENCES users(id);
ALTER TABLE shifts ADD COLUMN IF NOT EXISTS reviewed_at TIMESTAMP;
ALTER TABLE shifts ADD COLUMN IF NOT EXISTS review_note TEXT;
