#!/usr/bin/env bash
# Khởi chạy Docker stack + ngrok (BE:8080, FE:5173) + cấu hình VITE_API_URL cho frontend.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
COMPOSE_FILE="$ROOT/docker/docker-compose.yaml"
NGROK_CFG="$ROOT/ngrok/ngrok.yml"
ENV_LOCAL="$ROOT/frontend/.env.local"
PID_DIR="$ROOT/.ngrok-run"
BE_PID="$PID_DIR/ngrok.pid"
FE_PID="$PID_DIR/vite.pid"
NGROK_API_PORT=""

mkdir -p "$PID_DIR"

die() { echo "ERROR: $*" >&2; exit 1; }

ngrok_api_port() {
  local p
  for p in 4040 4041 4042 4043; do
    if curl -sf "http://127.0.0.1:${p}/api/tunnels" >/dev/null 2>&1; then
      echo "$p"
      return 0
    fi
  done
  return 1
}

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "Thiếu lệnh '$1'. Cài đặt rồi chạy lại."
}

stop_if_running() {
  local pidfile="$1"
  if [[ -f "$pidfile" ]]; then
    local pid
    pid="$(cat "$pidfile")"
    if kill -0 "$pid" 2>/dev/null; then
      kill "$pid" 2>/dev/null || true
      sleep 1
    fi
    rm -f "$pidfile"
  fi
}

tunnel_url() {
  local name="$1"
  local port="${NGROK_API_PORT:-4040}"
  python3 - <<PY "$name" "$port"
import json, sys, urllib.request
name, port = sys.argv[1], sys.argv[2]
try:
    with urllib.request.urlopen(f"http://127.0.0.1:{port}/api/tunnels", timeout=5) as r:
        data = json.load(r)
except Exception:
    sys.exit(1)
for t in data.get("tunnels", []):
    if t.get("name") == name:
        print(t["public_url"])
        sys.exit(0)
sys.exit(1)
PY
}

echo "=== SmartMart ngrok setup ==="

require_cmd ngrok
require_cmd docker
require_cmd python3

if ! ngrok config check >/dev/null 2>&1; then
  die "Chưa cấu hình ngrok authtoken. Chạy: ngrok config add-authtoken <TOKEN>"
fi

echo "[1/5] Docker: postgres, redis, kafka, ai-service, backend (tắt frontend container)..."
if [[ "${REBUILD:-}" == "1" ]]; then
  docker compose -f "$COMPOSE_FILE" up -d --build postgres redis kafka ai-service backend
else
  docker compose -f "$COMPOSE_FILE" up -d postgres redis kafka ai-service backend
fi
docker compose -f "$COMPOSE_FILE" stop frontend 2>/dev/null || true

echo "      Đợi backend healthy..."
for _ in $(seq 1 40); do
  if curl -sf "http://localhost:8080/v3/api-docs" >/dev/null 2>&1; then
    break
  fi
  sleep 2
done
curl -sf "http://localhost:8080/v3/api-docs" >/dev/null \
  || die "Backend chưa sẵn sàng trên :8080. Kiểm tra: docker compose -f $COMPOSE_FILE logs backend"

echo "[2/5] Dừng ngrok / Vite cũ (nếu có)..."
stop_if_running "$BE_PID"
stop_if_running "$FE_PID"
pkill -f "ngrok start" 2>/dev/null || true
sleep 1

echo "[3/5] Khởi động ngrok (backend + frontend)..."
ngrok start --all --config "$NGROK_CFG" --log=stdout >"$PID_DIR/ngrok.log" 2>&1 &
echo $! >"$BE_PID"

echo "      Đợi ngrok inspector + tunnel URLs..."
BE_URL=""
FE_URL=""
NGROK_API_PORT=""
for _ in $(seq 1 45); do
  NGROK_API_PORT="$(ngrok_api_port 2>/dev/null || true)"
  if [[ -n "$NGROK_API_PORT" ]]; then
    BE_URL="$(tunnel_url backend 2>/dev/null || true)"
    FE_URL="$(tunnel_url frontend 2>/dev/null || true)"
    if [[ -n "$BE_URL" && -n "$FE_URL" ]]; then
      break
    fi
  fi
  sleep 2
done
export NGROK_API_PORT
[[ -n "$BE_URL" ]] || die "Không lấy được URL tunnel backend. Kiểm tra mạng/VPN và xem $PID_DIR/ngrok.log"

echo "[4/5] Ghi frontend/.env.local → VITE_API_URL=$BE_URL"
cat >"$ENV_LOCAL" <<EOF
# Auto-generated by scripts/ngrok-setup.sh — không commit
VITE_API_URL=$BE_URL
EOF

echo "[5/5] Khởi động Vite dev server (:5173)..."
if [[ ! -d "$ROOT/frontend/node_modules" ]]; then
  (cd "$ROOT/frontend" && npm install --silent)
fi
(cd "$ROOT/frontend" && npm run dev -- --host 0.0.0.0 --port 5173) >"$PID_DIR/vite.log" 2>&1 &
echo $! >"$FE_PID"

for _ in $(seq 1 20); do
  if curl -sf "http://localhost:5173/" >/dev/null 2>&1; then
    break
  fi
  sleep 1
done

# Refresh FE tunnel URL after Vite is up
FE_URL="$(tunnel_url frontend 2>/dev/null || true)"

echo ""
echo "=============================================="
echo "  SmartMart public URLs (ngrok)"
echo "=============================================="
echo "  API + Swagger:  $BE_URL/swagger-ui/index.html"
echo "  API base:       $BE_URL/api/v1/"
echo "  Frontend:       ${FE_URL:-https://<xem ngrok dashboard :4040>}"
echo ""
echo "  Login demo: admin / admin123"
echo "  Swagger: POST /api/v1/auth/login → Authorize Bearer <accessToken>"
echo ""
echo "  Dừng: $ROOT/scripts/ngrok-stop.sh"
echo "  Logs: tail -f $PID_DIR/ngrok.log  |  tail -f $PID_DIR/vite.log"
echo "=============================================="
